### PR TITLE
Add a method to clear the application local state

### PR DESCRIPTION
**Pull request by harisbotic**
Add Application.clear_state() method to clear the local state directory before the process starts.

Usage

```python
app.clear_state() # Clears the state of the application
app.run()
```

### CODE REVIEW

**Comment by ghost** [comment]
Hey @harisbotic , do I understand correctly that this `app.clear_state()` will work only after the StreamingDataFrame is defined?
Wouldn't it be easier to clean up the whole state directory for the given consumer group?

**Comment by harisbotic** [comment]
> Hey @harisbotic , do I understand correctly that this `app.clear_state()` will work only after the StreamingDataFrame is defined? Wouldn't it be easier to clean up the whole state directory for the given consumer group?

Actually the PR is not ready yet, when I added a test that tried to run `app.clear_state()` it failed to do so because it deletes the databases but doesn't re-create them. Which by current design should happen.  So I am fixing that first.

Regarding you comment, yes, we could do that as well, I didn't think of that

**Comment by harisbotic** [comment]
If we ever want to clear a single partition, here is how to do it:

```python
    def clear(self):
        """
        Clear all data from the store
        """
        logger.debug(
            f'Clearing store on: "{self._path}"',
        )

        self.close()
        self.destroy(self._path)
        self._db = self._init_db()

        logger.debug(
            f'Successfully cleared store on: "{self._path}"',
        )
        
```

with test:

```python
    def test_clear(self, rocksdb_partition_factory):
        with rocksdb_partition_factory() as storage:
            with storage.begin() as tx:
                tx.set("key", "value")

            assert storage.exists(serialize_key("key", dumps=dumps))
            storage.clear()
            assert not storage.exists(serialize_key("key", dumps=dumps))
```

**Comment by ghost** [comment]
Looks good! I like the approach, it's safer to check if the store has partitions assigned.
Could you please update the docs here too?
https://github.com/quixio/quix-streams/blob/main/src/StreamingDataFrames/docs/stateful-processing.md

**Review by ghost — APPROVED** [review]
LGTM 👍

**Pull request merged**
